
name: The CI file

on:
    workflow_dispatch:

    push:
        branches:
            - main

jobs:
    Containerize-job:
        runs-on: ubuntu-latest
        if: contains(github.event.head_commit.message, 'no-deploy') == false # check if "no-deploy" is in the commit message
        outputs:
            repo_owner_lower: ${{ steps.lowercase.outputs.repo_owner_lower }}
        steps:
            - uses: actions/checkout@v4
            
            - name: Login to GitHub Container Registry
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Convert repository owner to lowercase
              id: lowercase
              run: |
                  echo "repo_owner_lower=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
            
            - name: Setup docker build
              uses: docker/setup-buildx-action@v3 

            - name: Containerize and push the app
              uses: docker/build-push-action@v5
              with:
                context: .
                file: ./Dockerfile
                push: true
                tags: ghcr.io/${{ steps.lowercase.outputs.repo_owner_lower }}/agrihealth:v1-${{ github.sha }} 
          
    Deploy-job:
      needs: 
        - Containerize-job
      runs-on: ubuntu-latest
      steps:
        - name: Log in to Azure
          uses: azure/login@v1
          with:
            creds: ${{ secrets.AZURE_CREDS }}

        - name: Deploy to web app
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'agrihealth'
            package: '.'
            images: 'ghcr.io/${{ needs.Containerize-job.outputs.repo_owner_lower }}/agrihealth:v1-${{ github.sha }}'